@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDgxMDE5MTJ9.sSjbXjYulCgc03a3fTIJ9UWIsKYERX7uoCYer8_TK10

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "anna",
  "email": "anna@example.com",
  "password": "Password1-",
  "password_confirmation": "Password1-"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jasper1@example.com",
  "password": "Password"
}

### view orders
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### all products
GET http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### update products
PATCH http://localhost:3000/products/103.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "price":130
}

### delete products
DELETE http://localhost:3000/products/103
Authorization: Bearer {{jwt}}

### create products
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "name":"pens",
    "price":12,
    "description":"is niice",
    "supplier_id":2
}

