PATCH http://localhost:3000/product/3 
Content-Type: application/json

{
    "description":"its the fastest again!"
}

###

PATCH http://localhost:3000/products/104
Content-Type: application/json

{
    "price":"110"
}

###

DELETE http://localhost:3000/product/4

### create

POST http://localhost:3000/products.json
Content-Type: application/json

{
    "name":"goo",
    "price":140,
    "description":"hello"
}

